// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy2Bvqo6WosxdVCdPyaod5_MWCRZlR0AM',
    appId: '1:836445407377:web:ceb75dc12140ccbf2ed730',
    messagingSenderId: '836445407377',
    projectId: 'oddspro-ai',
    authDomain: 'oddspro-ai.firebaseapp.com',
    storageBucket: 'oddspro-ai.firebasestorage.app',
    measurementId: 'G-QZ6Z582PH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyATSeAfVFJ2--Curvx3BJDtpbMyK8Uy8',
    appId: '1:836445407377:android:e95dabbe35c0148a2ed730',
    messagingSenderId: '836445407377',
    projectId: 'oddspro-ai',
    storageBucket: 'oddspro-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByKrPRk5moMNQgpZd2oNVP68eo6Inuoik',
    appId: '1:836445407377:ios:ef80b15f8cae75362ed730',
    messagingSenderId: '836445407377',
    projectId: 'oddspro-ai',
    storageBucket: 'oddspro-ai.firebasestorage.app',
    iosClientId: '836445407377-nojb1sau0qbfg3r42pmu6u2ad1j71qaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.oddsproAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByKrPRk5moMNQgpZd2oNVP68eo6Inuoik',
    appId: '1:836445407377:ios:ef80b15f8cae75362ed730',
    messagingSenderId: '836445407377',
    projectId: 'oddspro-ai',
    storageBucket: 'oddspro-ai.firebasestorage.app',
    iosClientId: '836445407377-nojb1sau0qbfg3r42pmu6u2ad1j71qaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.oddsproAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy2Bvqo6WosxdVCdPyaod5_MWCRZlR0AM',
    appId: '1:836445407377:web:49a958d09ef118a92ed730',
    messagingSenderId: '836445407377',
    projectId: 'oddspro-ai',
    authDomain: 'oddspro-ai.firebaseapp.com',
    storageBucket: 'oddspro-ai.firebasestorage.app',
    measurementId: 'G-VMJ9ET8VWN',
  );
}
